### ISSUE TITLE
Change Kyverno keys in policy to use config map

### ISSUE THREAD

**Issue by mlieberman85** [thesecuresoftwarefactory/ssf#10]
Based on conversation with @JimBugwadia recent commits on main now allow Kyverno to verify based on signing keys that are in a config map. Not just those hard coded into the policy resource.

From conversation:

Install latest image:
```
kubectl create -f https://raw.githubusercontent.com/kyverno/kyverno/main/definitions/release/install.yaml
```

Create configmap (replacing keys with ones we trust) like:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: keys
data:
  org: |-
    -----BEGIN PUBLIC KEY-----
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEHMmDjK65krAyDaGaeyWNzgvIu155
    JI50B2vezCw8+3CVeE0lJTL5dbL3OP98Za0oAEBJcOxky8Riy/XcmfKZbw==
    -----END PUBLIC KEY-----
  jimbugwadia: |-
    -----BEGIN PUBLIC KEY-----
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAES8du3JjhYT9/GFQ7/u2VwVGfCgup
    loAfx/LWRhWKidLFCSlXFOKFmjW1hFq5wJ3Mm7UFv3mV1D7w/BiGWmMrWw==
    -----END PUBLIC KEY-----
```

Create policy like:
```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-image
spec:
  validationFailureAction: enforce
  background: false
  webhookTimeoutSeconds: 30
  failurePolicy: Fail  
  rules:
    - name: check-image
      match:
        resources:
          kinds:
            - Pod
      context:
      - name: keys
        configMap:
          name: keys
          namespace: default 
      verifyImages:
      - image: "*"
        key: "{{ keys.data.org }}"
      - image: "ghcr.io/jimbugwadia/*"
        key: "{{ keys.data.jimbugwadia }}"
```
